name: Build and deploy Streamlit app to Azure Web App - buyer-app

on:
  push:
    branches:
      - buyer
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .streamlit config file
        run: |
          mkdir -p .streamlit
          echo "[server]" > .streamlit/config.toml
          echo "port = 8000" >> .streamlit/config.toml
          echo "enableCORS = false" >> .streamlit/config.toml
          echo "address = '0.0.0.0'" >> .streamlit/config.toml

      - name: Create run.sh startup script
        run: |
          echo "#!/bin/bash" > run.sh
          echo "pip install -r requirements.txt" >> run.sh
          echo "streamlit run app.py --server.port=8000 --server.address=0.0.0.0" >> run.sh
          chmod +x run.sh

      - name: Zip app for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: streamlit-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B039F3EA59D247D09E20C1192E5DD8C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8660FEB67A864A29955A88AE16B5CE51 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D5263E7D396343B184ACBE5982B4D8CA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'buyer-app'
          slot-name: 'Production'
          package: release.zip
          startup-command: "bash run.sh"
